(package "lsp-ui"
         "8.0.0"
         "UI modules for lsp-mode")

(package-file "lsp-ui.el")

(files "*.el" "lsp-ui-doc.html")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.3")
(depends-on "dash")
(depends-on "flycheck")
(depends-on "lsp-mode")
(depends-on "markdown-mode")
(depends-on "rustic")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
